import { NextResponse } from 'next/server'
import uniqueId from 'lodash/uniqueId'
import dayjs from 'dayjs'
import sleep from '@/utils/sleep'

export async function POST(req) {
    const { prompt } = await req.json()

    const userPrompt = prompt.toLocaleLowerCase()

    const responseContents = {
        regular: [
            `Bienvenido a Tip Edge Plus.`,
        ],
        title: 'This is a mock response with a title.\n\n###### Example Title\n\nPlease note that this is not generated by an actual AI model.',
        code: "This is a mock response with a code snippet.\n\n```\nfunction example() {\n    console.log('This is a mock code snippet.');\n}\n```\n\nPlease note that this is not generated by an actual AI model.",
        list: 'This is a mock response with a list.\n\n1. First item\n2. Second item\n3. Third item\n\nPlease note that this is not generated by an actual AI model.',
    }

    let content =
        responseContents.regular[
            Math.floor(Math.random() * responseContents.regular.length)
        ]

    if (userPrompt.includes('title')) {
        content = responseContents.title
    }
    if (userPrompt.includes('code')) {
        content = responseContents.code
    }
    if (userPrompt.includes('list')) {
        content = responseContents.list
    }

    const response = {
        id: uniqueId('ai-conversation-'),
        choices: [
            {
                finish_reason: 'stop',
                index: 0,
                message: {
                    content: content,
                    role: 'assistant',
                },
            },
        ],
        created: dayjs().unix(),
        model: 'gpt-4',
    }

    await sleep(200)

    return NextResponse.json(response)
}
